name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Bump patch version
        id: bump_version
        run: |
          git pull origin main
          VERSION=$(cat version.txt)
          echo "Current version: $VERSION"
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "$NEW_VERSION" > version.txt
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit and push new version
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull origin main --rebase --autostash
          git add version.txt
          git commit -m "Bump version to ${{ steps.bump_version.outputs.version }}" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:main

      - name: Build Docker image
        run: |
          IMAGE_NAME=simple-java-maven-app
          VERSION=${{ steps.bump_version.outputs.version }}
          docker build -t $IMAGE_NAME:$VERSION .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          IMAGE_NAME=simple-java-maven-app
          VERSION=${{ steps.bump_version.outputs.version }}
          docker tag $IMAGE_NAME:$VERSION ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$VERSION
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$VERSION
